import { Recipe } from "../../recipes";

export const testData: Recipe = {
  approved_at: 1523907123,
  aspect_ratio: "1:1",
  beauty_url:
    "https://img.buzzfeed.com/video-api-prod/assets/15cf3ad98d504be0abbfd2efa30c5c5a/BFV35527_100LayerLasagna-Beauty.jpg",
  brand: null,
  brand_id: null,
  buzz_id: null,
  canonical_id: "recipe:3746",
  compilations: [
    {
      approved_at: 1525404431,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:554",
      country: "US",
      created_at: 1525373465,
      description: null,
      draft_status: "published",
      facebook_posts: [],
      id: 554,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "5 Mind-Blowing Layered Recipes",
      promotion: "full",
      show: [
        {
          id: 51,
          name: "Tasty: Tasty Grill",
        },
      ],
      slug: "5-mind-blowing-layered-recipes",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/154133.jpg",
      video_id: 55315,
      video_url: "https://vid.tasty.co/output/92413/hls24_1525369560.m3u8",
    },
    {
      approved_at: 1546553358,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:834",
      country: "US",
      created_at: 1545433195,
      description: null,
      draft_status: "published",
      facebook_posts: [],
      id: 834,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "6 Most-Popular Tasty Recipe Videos Of The Year",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "best-of-the-year-6-most-watched-tasty-recipe-videos",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/198462.jpg",
      video_id: 74859,
      video_url: "https://vid.tasty.co/output/121124/hls24_1545433315.m3u8",
    },
    {
      approved_at: 1557975833,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:951",
      country: "US",
      created_at: 1557836218,
      description: null,
      draft_status: "published",
      facebook_posts: [],
      id: 951,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "Tasty's Cheesiest Lasagna Recipes",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "tasty-s-cheesiest-lasagna-recipes",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/216141.jpg",
      video_id: 82747,
      video_url: "https://vid.tasty.co/output/132723/hls24_1557836770.m3u8",
    },
    {
      approved_at: 1583891663,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:1432",
      country: "US",
      created_at: 1583851515,
      description: null,
      draft_status: "published",
      facebook_posts: [],
      id: 1432,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "12 Extra Cheesy Layered Lasagna Recipes",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "12-extra-cheesy-layered-lasagna-recipes",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/257124.jpg",
      video_id: 99978,
      video_url: "https://vid.tasty.co/output/161574/hls24_1582991941.m3u8",
    },
    {
      approved_at: 1600108969,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:1684",
      country: "US",
      created_at: 1598896707,
      description:
        'Having trouble deciding what you should make next? Take a look at a few of the best pasta recipes we have to offer! From a <a href="https://tasty.co/recipe/vegan-mac-n-cheese">vegan version of mac \'n\' cheese</a> to delicious <a href="https://tasty.co/recipe/spaghetti-meatball-bake">baked meatballs and spaghetti</a>, these ideas will satisfy every craving. Pair your pasta with a salad, dessert, and glass of wine — and you\'ve got a restaurant-quality menu right at home!',
      draft_status: "published",
      facebook_posts: [],
      id: 1684,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "Tasty's Best Pasta Recipes",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "tasty-s-best-pasta-recipes",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/281005.jpg",
      video_id: 112179,
      video_url: "https://vid.tasty.co/output/177582/hls24_1598903165.m3u8",
    },
    {
      approved_at: 1601298662,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:1711",
      country: "US",
      created_at: 1600174492,
      description: null,
      draft_status: "published",
      facebook_posts: [],
      id: 1711,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "Over-The-Top Recipes To Procrastinate Studying Over",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "over-the-top-recipes-to-procrastinate-studying-over",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/283019.jpg",
      video_id: 113584,
      video_url: "https://vid.tasty.co/output/178874/hls24_1600177466.m3u8",
    },
    {
      approved_at: 1607958478,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:1892",
      country: "US",
      created_at: 1606914115,
      description: null,
      draft_status: "published",
      facebook_posts: [],
      id: 1892,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "Tasty's Favorite Giant Foods",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "tasty-s-favorite-giant-foods",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/296751.jpg",
      video_id: 118711,
      video_url: "https://vid.tasty.co/output/187008/hls24_1606914812.m3u8",
    },
    {
      approved_at: 1668718685,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:3317",
      country: "US",
      created_at: 1663562528,
      description:
        'Big family dinners are a time for everyone to come together and gather around a table full of delicious eats. Impress everyone with these family-friendly (and family-size!) recipes that are sure to satisfy the whole crew. From a never-ending <a href="https://tasty.co/recipe/100-layer-lasagna"> 100-Layer Lasagna </a> to a filling <a href="https://tasty.co/recipe/chili-cheese-casserole"> Chili Cheese Casserole</a> , these dishes will have everyone coming back for more!',
      draft_status: "published",
      facebook_posts: [],
      id: 3317,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "Recipes to Cook For a Big Family Dinner!",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "recipes-to-cook-for-a-big-family-dinner",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://s3.amazonaws.com/video-api-prod/assets/fa68916e941d481c99136a1051905e44/aaa.jpg",
      video_id: 168422,
      video_url: "https://vid.tasty.co/output/254537/hls24_1663561511.m3u8",
    },
    {
      approved_at: 1668699347,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:3351",
      country: "US",
      created_at: 1667197570,
      description: null,
      draft_status: "published",
      facebook_posts: [],
      id: 3351,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "Tasty's Greatest Bites Of All Time",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "tasty-s-greatest-bites-of-all-time",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/408066.jpg",
      video_id: 172547,
      video_url: "https://vid.tasty.co/output/260391/hls24_1667364329.m3u8",
    },
    {
      approved_at: 1670358181,
      aspect_ratio: "1:1",
      beauty_url: null,
      buzz_id: null,
      canonical_id: "compilation:3370",
      country: "US",
      created_at: 1668765961,
      description:
        'End the year with a culinary big bang! 2022 is coming to an end, but your nights shouldn\'t without tasting these delicious recipes. We have got <a href="https://tasty.co/recipe/baked-lobster-tails">Baked Lobster Tails</a>, <a href="https://tasty.co/recipe/creamy-tuscan-chicken">Creamy Tuscan Chicken</a>, <a href="https://tasty.co/recipe/korean-style-bbq-beef">Korean-Style BBQ Beef</a>, or a <a href="https://tasty.co/recipe/20-minute-one-pan-pizza">20-Minute One-Pan Pizza</a> to cover all of your cravings. Are you convinced or should we go on?',
      draft_status: "published",
      facebook_posts: [],
      id: 3370,
      is_shoppable: false,
      keywords: null,
      language: "eng",
      name: "Tasty Dinners for Every Night of December",
      promotion: "full",
      show: [
        {
          id: 17,
          name: "Tasty",
        },
      ],
      slug: "tasty-dinner-for-every-night-of-december",
      thumbnail_alt_text: "",
      thumbnail_url:
        "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/411506.jpg",
      video_id: 174237,
      video_url: "https://vid.tasty.co/output/264409/hls24_1669870722.m3u8",
    },
  ],
  cook_time_minutes: 270,
  country: "US",
  created_at: 1523835443,
  credits: [
    {
      name: "Alvin Zhou",
      type: "internal",
    },
  ],
  description:
    "You won't believe your eyes when you see this 100-layer lasagna! It's a tower of deliciousness filled with layers of pasta, meat sauce, ricotta cheese, and mozzarella cheese. It's like a work of art that you can eat!",
  draft_status: "published",
  facebook_posts: [],
  id: 3746,
  inspired_by_url: null,
  instructions: [
    {
      appliance: null,
      display_text:
        "Lay down about 6 feet (1.8 meters) of tinfoil on a flat surface. Place place 4 clusters of 2 lasagna noodles towards the left half of the foil sheet, leaving about a ½-inch (1 cm) gap in between each cluster.",
      end_time: 12883,
      id: 32688,
      position: 1,
      start_time: 2833,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Fold the right half of foil over the noodles, pressing flat. To help you see where the noodles are, run your finger along the edges of the noodles to create a rough outline in the foil.",
      end_time: 19383,
      id: 32689,
      position: 2,
      start_time: 12883,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Fold the top and bottom flaps of foil over, creasing and pressing flat.",
      end_time: 20716,
      id: 32690,
      position: 3,
      start_time: 19550,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Flip the foil sheet onto the table so that it’s now standing, then arrange into a square box, using the 4 groups of noodles as a visual guide. Fold and crease over any excess foil to join the ends together, then set aside.",
      end_time: 23216,
      id: 32691,
      position: 4,
      start_time: 20716,
      temperature: null,
    },
    {
      appliance: null,
      display_text: "In a large pot, melt the butter over medium heat.",
      end_time: 27049,
      id: 32692,
      position: 5,
      start_time: 24216,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Whisk in the flour, cooking until the mixture reaches a light golden color.",
      end_time: 32766,
      id: 32693,
      position: 6,
      start_time: 27216,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Slowly drizzle in the milk and bring to a boil, whisking constantly until smooth. Mix in salt, pepper, and nutmeg. Bring to a boil.",
      end_time: 45766,
      hacks: [
        {
          end_index: 45,
          id: 18,
          match: "boil",
          start_index: 42,
        },
        {
          end_index: 55,
          id: 24,
          match: "whisking",
          start_index: 48,
        },
      ],
      id: 32694,
      position: 7,
      start_time: 32933,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Transfer the béchamel to a large bowl and press plastic wrap onto the surface of the sauce to prevent a skin from forming. Set aside.",
      end_time: 0,
      id: 32695,
      position: 8,
      start_time: 0,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Heat oil in a very large pot over high heat. Once the oil begins to shimmer, add the onions, carrots, and celery and cook until the vegetables have started to sweat but aren’t browning.",
      end_time: 52983,
      hacks: [
        {
          end_index: 183,
          id: 13,
          match: "browning",
          start_index: 176,
        },
      ],
      id: 32696,
      position: 9,
      start_time: 46766,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Add in the ground beef and use a wooden spoon or spatula to break up the meat into small pieces.",
      end_time: 55666,
      id: 32697,
      position: 10,
      start_time: 53150,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Cook the beef, stirring occasionally, until half of the liquid has evaporated.",
      end_time: 58333,
      id: 32698,
      position: 11,
      start_time: 55666,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Add in the tomato sauce, tomato paste, chicken stock, salt, and pepper, stirring to combine evenly and breaking up any last lumps.",
      end_time: 73716,
      id: 32699,
      position: 12,
      start_time: 58500,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Turn down the heat to low, and simmer, covered, for about 2 hours.",
      end_time: 0,
      hacks: [
        {
          end_index: 36,
          id: 17,
          match: "simmer",
          start_index: 31,
        },
      ],
      id: 32700,
      position: 13,
      start_time: 0,
      temperature: null,
    },
    {
      appliance: "oven",
      display_text: "Preheat oven to 350°F (180°C).",
      end_time: 0,
      id: 32687,
      position: 14,
      start_time: 0,
      temperature: 350,
    },
    {
      appliance: null,
      display_text:
        "To assemble, line a greased 9x9-inch (23x23-cm) square baking pan with 2 sheets of foil that extend over the sides.",
      end_time: 87100,
      id: 32701,
      position: 15,
      start_time: 82550,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Spread a thin layer of béchamel on the lined baking pan and top with 2 lasagna noodles. Spread a thin layer of meat sauce evenly across the noodles, followed by a thin layer of béchamel. Repeat the layering process, following the order of: 2 noodles, meat sauce, and béchamel. Alternate the direction of the lasagna sheets after every layer.",
      end_time: 110483,
      id: 32702,
      position: 16,
      start_time: 87266,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "After 50 layers, place the foil box over the lasagna, helping it stay upright and stable.",
      end_time: 117816,
      id: 32703,
      position: 17,
      start_time: 110650,
      temperature: null,
    },
    {
      appliance: null,
      display_text: "Continue with the layering process until the 99th layer.",
      end_time: 136366,
      id: 32704,
      position: 18,
      start_time: 117983,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Sprinkle Parmesan on top, then cover the whole lasagna with foil.",
      end_time: 148700,
      id: 32705,
      position: 19,
      start_time: 136366,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Bake for about 1½ hours, uncovering the foil halfway, until the top is a deep golden brown.",
      end_time: 0,
      id: 32706,
      position: 20,
      start_time: 0,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Cool for at least 2 hours, then carefully lift out the lasagna with the foil sleeves onto a large cutting board.",
      end_time: 0,
      id: 32707,
      position: 21,
      start_time: 0,
      temperature: null,
    },
    {
      appliance: null,
      display_text:
        "Peel away the foil walls, then sprinkle the top of the lasagna generously with chives.",
      end_time: 162416,
      id: 32708,
      position: 22,
      start_time: 154700,
      temperature: null,
    },
    {
      appliance: null,
      display_text: "Cut and serve.",
      end_time: 186966,
      id: 32709,
      position: 23,
      start_time: 163916,
      temperature: null,
    },
    {
      appliance: null,
      display_text: "Enjoy!",
      end_time: 195683,
      id: 32721,
      position: 24,
      start_time: 188466,
      temperature: null,
    },
  ],
  is_app_only: false,
  is_one_top: false,
  is_shoppable: true,
  is_subscriber_content: false,
  keywords:
    "100 layer lasagna, behind the scenes 100 layer lasagna, how to make lasagna, hundred layer lasagna, lasagna recipe, tasty lasagna",
  language: "eng",
  name: "100-Layer Lasagna",
  num_servings: 20,
  nutrition: {
    calories: 747,
    carbohydrates: 46,
    fat: 32,
    fiber: 5,
    protein: 52,
    sugar: 15,
    updated_at: "2024-09-03T03:10:44+02:00",
  },
  nutrition_visibility: "auto",
  original_video_url:
    "https://s3.amazonaws.com/video-api-prod/assets/d6ca0a1f356141049705f49d48aecc5d/BFV35527_100LayerLasagna-FBFINAL.mp4",
  prep_time_minutes: 180,
  price: {
    consumption_portion: 250,
    consumption_total: 4700,
    portion: 300,
    total: 5650,
    updated_at: "2024-10-24T07:04:42+02:00",
  },
  promotion: "partial",
  renditions: [
    {
      aspect: "square",
      bit_rate: 2597,
      container: "mp4",
      content_type: "video/mp4",
      duration: 207122,
      file_size: 67222368,
      height: 720,
      maximum_bit_rate: null,
      minimum_bit_rate: null,
      name: "mp4_720x720",
      poster_url:
        "https://img.buzzfeed.com/video-transcoder-prod/output/89658/square_720/1523902408_00001.png",
      url: "https://vid.tasty.co/output/89658/square_720/1523902408",
      width: 720,
    },
    {
      aspect: "square",
      bit_rate: 875,
      container: "mp4",
      content_type: "video/mp4",
      duration: 207122,
      file_size: 22630857,
      height: 320,
      maximum_bit_rate: null,
      minimum_bit_rate: null,
      name: "mp4_320x320",
      poster_url:
        "https://img.buzzfeed.com/video-transcoder-prod/output/89658/square_320/1523902408_00001.png",
      url: "https://vid.tasty.co/output/89658/square_320/1523902408",
      width: 320,
    },
    {
      aspect: "square",
      bit_rate: 2594,
      container: "mp4",
      content_type: "video/mp4",
      duration: 207122,
      file_size: 67155286,
      height: 720,
      maximum_bit_rate: null,
      minimum_bit_rate: null,
      name: "mp4_720x720",
      poster_url:
        "https://img.buzzfeed.com/video-transcoder-prod/output/89658/landscape_720/1523902408_00001.png",
      url: "https://vid.tasty.co/output/89658/landscape_720/1523902408",
      width: 720,
    },
    {
      aspect: "square",
      bit_rate: 1496,
      container: "mp4",
      content_type: "video/mp4",
      duration: 207122,
      file_size: 38707125,
      height: 480,
      maximum_bit_rate: null,
      minimum_bit_rate: null,
      name: "mp4_480x480",
      poster_url:
        "https://img.buzzfeed.com/video-transcoder-prod/output/89658/landscape_480/1523902408_00001.png",
      url: "https://vid.tasty.co/output/89658/landscape_480/1523902408",
      width: 480,
    },
    {
      aspect: "square",
      bit_rate: null,
      container: "ts",
      content_type: "application/vnd.apple.mpegurl",
      duration: 207124,
      file_size: null,
      height: 1080,
      maximum_bit_rate: 4514,
      minimum_bit_rate: 272,
      name: "low",
      poster_url:
        "https://img.buzzfeed.com/video-transcoder-prod/output/89658/1445289064805-h2exzu/1523902408_00001.png",
      url: "https://vid.tasty.co/output/89658/hls24_1523902408.m3u8",
      width: 1080,
    },
  ],
  sections: [
    {
      components: [
        {
          extra_comment: "",
          id: 37335,
          ingredient: {
            created_at: 1493314940,
            display_plural: "butters",
            display_singular: "butter",
            id: 30,
            name: "butter",
            updated_at: 1509035287,
          },
          measurements: [
            {
              id: 440589,
              quantity: "1",
              unit: {
                abbreviation: "stick",
                display_plural: "sticks",
                display_singular: "stick",
                name: "stick",
                system: "none",
              },
            },
          ],
          position: 2,
          raw_text: "1 stick butter",
        },
        {
          extra_comment: "",
          id: 37336,
          ingredient: {
            created_at: 1493314654,
            display_plural: "flours",
            display_singular: "flour",
            id: 25,
            name: "flour",
            updated_at: 1509035288,
          },
          measurements: [
            {
              id: 440603,
              quantity: "½",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440601,
              quantity: "60",
              unit: {
                abbreviation: "g",
                display_plural: "g",
                display_singular: "g",
                name: "gram",
                system: "metric",
              },
            },
          ],
          position: 3,
          raw_text: "½ cup flour",
        },
        {
          extra_comment: "",
          id: 37337,
          ingredient: {
            created_at: 1493314636,
            display_plural: "milks",
            display_singular: "milk",
            id: 21,
            name: "milk",
            updated_at: 1509035288,
          },
          measurements: [
            {
              id: 440593,
              quantity: "8",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440590,
              quantity: "2",
              unit: {
                abbreviation: "L",
                display_plural: "L",
                display_singular: "L",
                name: "liter",
                system: "metric",
              },
            },
          ],
          position: 4,
          raw_text: "8 cups milk",
        },
        {
          extra_comment: "",
          id: 37338,
          ingredient: {
            created_at: 1493314644,
            display_plural: "salts",
            display_singular: "salt",
            id: 22,
            name: "salt",
            updated_at: 1509035288,
          },
          measurements: [
            {
              id: 440599,
              quantity: "2",
              unit: {
                abbreviation: "tsp",
                display_plural: "teaspoons",
                display_singular: "teaspoon",
                name: "teaspoon",
                system: "imperial",
              },
            },
          ],
          position: 5,
          raw_text: "2 teaspoons salt",
        },
        {
          extra_comment: "",
          id: 37339,
          ingredient: {
            created_at: 1493307183,
            display_plural: "black peppers",
            display_singular: "black pepper",
            id: 12,
            name: "black pepper",
            updated_at: 1509035289,
          },
          measurements: [
            {
              id: 440594,
              quantity: "1",
              unit: {
                abbreviation: "tsp",
                display_plural: "teaspoons",
                display_singular: "teaspoon",
                name: "teaspoon",
                system: "imperial",
              },
            },
          ],
          position: 6,
          raw_text: "1 teaspoon black pepper",
        },
        {
          extra_comment: "",
          id: 37340,
          ingredient: {
            created_at: 1495588355,
            display_plural: "nutmegs",
            display_singular: "nutmeg",
            id: 677,
            name: "nutmeg",
            updated_at: 1509035242,
          },
          measurements: [
            {
              id: 440600,
              quantity: "½",
              unit: {
                abbreviation: "tsp",
                display_plural: "teaspoons",
                display_singular: "teaspoon",
                name: "teaspoon",
                system: "imperial",
              },
            },
          ],
          position: 7,
          raw_text: "½ teaspoon nutmeg",
        },
      ],
      name: "Béchamel Sauce",
      position: 1,
    },
    {
      components: [
        {
          extra_comment: "",
          id: 37342,
          ingredient: {
            created_at: 1493306183,
            display_plural: "olive oils",
            display_singular: "olive oil",
            id: 4,
            name: "olive oil",
            updated_at: 1509035290,
          },
          measurements: [
            {
              id: 440596,
              quantity: "½",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440595,
              quantity: "120",
              unit: {
                abbreviation: "mL",
                display_plural: "mL",
                display_singular: "mL",
                name: "milliliter",
                system: "metric",
              },
            },
          ],
          position: 9,
          raw_text: "½ cup olive oil",
        },
        {
          extra_comment: "finely chopped",
          hacks: [
            {
              end_index: 27,
              id: 1,
              match: "chopped",
              start_index: 21,
            },
          ],
          id: 37343,
          ingredient: {
            created_at: 1493311386,
            display_plural: "onions",
            display_singular: "onion",
            id: 17,
            name: "onion",
            updated_at: 1509035288,
          },
          measurements: [
            {
              id: 440592,
              quantity: "2",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440591,
              quantity: "300",
              unit: {
                abbreviation: "g",
                display_plural: "g",
                display_singular: "g",
                name: "gram",
                system: "metric",
              },
            },
          ],
          position: 10,
          raw_text: "2 cups onion, finely chopped",
        },
        {
          extra_comment: "finely chopped",
          hacks: [
            {
              end_index: 29,
              id: 1,
              match: "chopped",
              start_index: 23,
            },
          ],
          id: 37344,
          ingredient: {
            created_at: 1493314877,
            display_plural: "carrots",
            display_singular: "carrot",
            id: 27,
            name: "carrot",
            updated_at: 1509035288,
          },
          measurements: [
            {
              id: 440606,
              quantity: "2",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440605,
              quantity: "240",
              unit: {
                abbreviation: "g",
                display_plural: "g",
                display_singular: "g",
                name: "gram",
                system: "metric",
              },
            },
          ],
          position: 11,
          raw_text: "2 cups carrots, finely chopped",
        },
        {
          extra_comment: "finely chopped",
          hacks: [
            {
              end_index: 28,
              id: 1,
              match: "chopped",
              start_index: 22,
            },
          ],
          id: 37345,
          ingredient: {
            created_at: 1495082620,
            display_plural: "celeries",
            display_singular: "celery",
            id: 458,
            name: "celery",
            updated_at: 1509035259,
          },
          measurements: [
            {
              id: 440604,
              quantity: "2",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440602,
              quantity: "450",
              unit: {
                abbreviation: "g",
                display_plural: "g",
                display_singular: "g",
                name: "gram",
                system: "metric",
              },
            },
          ],
          position: 12,
          raw_text: "2 cups celery, finely chopped",
        },
        {
          extra_comment: "80% lean 20% fat",
          id: 37346,
          ingredient: {
            created_at: 1493920746,
            display_plural: "ground beefs",
            display_singular: "ground beef",
            id: 161,
            name: "ground beef",
            updated_at: 1509035282,
          },
          measurements: [
            {
              id: 440598,
              quantity: "6",
              unit: {
                abbreviation: "lb",
                display_plural: "lb",
                display_singular: "lb",
                name: "pound",
                system: "imperial",
              },
            },
            {
              id: 440597,
              quantity: "2.5",
              unit: {
                abbreviation: "kg",
                display_plural: "kg",
                display_singular: "kg",
                name: "kilogram",
                system: "metric",
              },
            },
          ],
          position: 13,
          raw_text: "6 pounds ground beef, 80% lean 20% fat",
        },
        {
          extra_comment: "4 cans",
          id: 37347,
          ingredient: {
            created_at: 1494882012,
            display_plural: "tomato sauces",
            display_singular: "tomato sauce",
            id: 344,
            name: "tomato sauce",
            updated_at: 1509035268,
          },
          measurements: [
            {
              id: 440614,
              quantity: "115",
              unit: {
                abbreviation: "oz",
                display_plural: "oz",
                display_singular: "oz",
                name: "ounce",
                system: "imperial",
              },
            },
            {
              id: 440612,
              quantity: "3.5",
              unit: {
                abbreviation: "kg",
                display_plural: "kg",
                display_singular: "kg",
                name: "kilogram",
                system: "metric",
              },
            },
          ],
          position: 14,
          raw_text: "4 28-ounce cans tomato sauce",
        },
        {
          extra_comment: "",
          id: 37348,
          ingredient: {
            created_at: 1495078295,
            display_plural: "tomato pastes",
            display_singular: "tomato paste",
            id: 456,
            name: "tomato paste",
            updated_at: 1509035259,
          },
          measurements: [
            {
              id: 440608,
              quantity: "½",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440607,
              quantity: "110",
              unit: {
                abbreviation: "g",
                display_plural: "g",
                display_singular: "g",
                name: "gram",
                system: "metric",
              },
            },
          ],
          position: 15,
          raw_text: "½ cup tomato paste",
        },
        {
          extra_comment: "",
          id: 37349,
          ingredient: {
            created_at: 1494124570,
            display_plural: "chicken stocks",
            display_singular: "chicken stock",
            id: 196,
            name: "chicken stock",
            updated_at: 1509035280,
          },
          measurements: [
            {
              id: 440610,
              quantity: "4",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440609,
              quantity: "960",
              unit: {
                abbreviation: "mL",
                display_plural: "mL",
                display_singular: "mL",
                name: "milliliter",
                system: "metric",
              },
            },
          ],
          position: 16,
          raw_text: "4 cups chicken stock",
        },
        {
          extra_comment: "",
          id: 37350,
          ingredient: {
            created_at: 1493314644,
            display_plural: "salts",
            display_singular: "salt",
            id: 22,
            name: "salt",
            updated_at: 1509035288,
          },
          measurements: [
            {
              id: 440617,
              quantity: "1",
              unit: {
                abbreviation: "tbsp",
                display_plural: "tablespoons",
                display_singular: "tablespoon",
                name: "tablespoon",
                system: "imperial",
              },
            },
          ],
          position: 17,
          raw_text: "1 tablespoon salt",
        },
        {
          extra_comment: "",
          id: 37351,
          ingredient: {
            created_at: 1493307183,
            display_plural: "black peppers",
            display_singular: "black pepper",
            id: 12,
            name: "black pepper",
            updated_at: 1509035289,
          },
          measurements: [
            {
              id: 440611,
              quantity: "½",
              unit: {
                abbreviation: "tbsp",
                display_plural: "tablespoons",
                display_singular: "tablespoon",
                name: "tablespoon",
                system: "imperial",
              },
            },
          ],
          position: 18,
          raw_text: "½ tablespoon black pepper",
        },
        {
          extra_comment: "",
          hacks: [
            {
              end_index: 10,
              id: 18,
              match: "boil",
              start_index: 7,
            },
          ],
          id: 37352,
          ingredient: {
            created_at: 1523904949,
            display_plural: "no-boil flat lasagna noodles",
            display_singular: "no-boil flat lasagna noodle",
            id: 3969,
            name: "no-boil flat lasagna noodle",
            updated_at: 1523904949,
          },
          measurements: [
            {
              id: 440616,
              quantity: "110",
              unit: {
                abbreviation: "",
                display_plural: "",
                display_singular: "",
                name: "",
                system: "none",
              },
            },
          ],
          position: 19,
          raw_text: "108 no-boil flat lasagna noodles",
        },
        {
          extra_comment: "",
          id: 37353,
          ingredient: {
            created_at: 1497741203,
            display_plural: "grated parmesan cheeses",
            display_singular: "grated parmesan cheese",
            id: 1869,
            name: "grated parmesan cheese",
            updated_at: 1509035159,
          },
          measurements: [
            {
              id: 440615,
              quantity: "2",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440613,
              quantity: "220",
              unit: {
                abbreviation: "g",
                display_plural: "g",
                display_singular: "g",
                name: "gram",
                system: "metric",
              },
            },
          ],
          position: 20,
          raw_text: "2 cups grated Parmesan",
        },
        {
          extra_comment: "finely chopped",
          hacks: [
            {
              end_index: 27,
              id: 1,
              match: "chopped",
              start_index: 21,
            },
          ],
          id: 37354,
          ingredient: {
            created_at: 1498567386,
            display_plural: "fresh chives",
            display_singular: "fresh chive",
            id: 1947,
            name: "fresh chives",
            updated_at: 1509035154,
          },
          measurements: [
            {
              id: 440619,
              quantity: "1",
              unit: {
                abbreviation: "c",
                display_plural: "cups",
                display_singular: "cup",
                name: "cup",
                system: "imperial",
              },
            },
            {
              id: 440618,
              quantity: "40",
              unit: {
                abbreviation: "g",
                display_plural: "g",
                display_singular: "g",
                name: "gram",
                system: "metric",
              },
            },
          ],
          position: 21,
          raw_text: "1 cup chives, finely chopped",
        },
      ],
      name: "Meat Sauce",
      position: 2,
    },
  ],
  seo_path: "9295813,64486,9299522,9299622",
  seo_title: null,
  servings_noun_plural: "servings",
  servings_noun_singular: "serving",
  show: {
    id: 17,
    name: "Tasty",
  },
  show_id: 17,
  slug: "100-layer-lasagna",
  tags: [
    {
      display_name: "North American",
      id: 64444,
      name: "north_american",
      parent_tag_name: "cuisine",
      root_tag_type: "cuisine",
      type: "cuisine",
    },
    {
      display_name: "Italian",
      id: 64453,
      name: "italian",
      parent_tag_name: "european",
      root_tag_type: "cuisine",
      type: "european",
    },
    {
      display_name: "Comfort Food",
      id: 64462,
      name: "comfort_food",
      parent_tag_name: "cooking_style",
      root_tag_type: "cooking_style",
      type: "cooking_style",
    },
    {
      display_name: "Dinner",
      id: 64486,
      name: "dinner",
      parent_tag_name: "meal",
      root_tag_type: "meal",
      type: "meal",
    },
    {
      display_name: "Baking",
      id: 64492,
      name: "baking",
      parent_tag_name: "appliance",
      root_tag_type: "appliance",
      type: "appliance",
    },
    {
      display_name: "Winter",
      id: 64511,
      name: "winter",
      parent_tag_name: "seasonal",
      root_tag_type: "seasonal",
      type: "seasonal",
    },
    {
      display_name: "Stove Top",
      id: 65848,
      name: "stove_top",
      parent_tag_name: null,
      root_tag_type: "appliance",
      type: "appliance",
    },
    {
      display_name: "Big Batch",
      id: 65851,
      name: "big_batch",
      parent_tag_name: "cooking_style",
      root_tag_type: "cooking_style",
      type: "cooking_style",
    },
    {
      display_name: "Special Occasion",
      id: 188967,
      name: "special_occasion",
      parent_tag_name: "occasion",
      root_tag_type: "seasonal",
      type: "occasion",
    },
    {
      display_name: "Oven Mitts",
      id: 1247775,
      name: "oven_mitts",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Sauce Pan",
      id: 1247786,
      name: "sauce_pan",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Spatula",
      id: 1247788,
      name: "spatula",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Whisk",
      id: 1247793,
      name: "whisk",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Baking Pan",
      id: 1280500,
      name: "baking_pan",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Chef's Knife",
      id: 1280501,
      name: "chefs_knife",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Liquid Measuring Cup",
      id: 1280506,
      name: "liquid_measuring_cup",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Dry Measuring Cups",
      id: 1280507,
      name: "dry_measuring_cups",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Measuring Spoons",
      id: 1280508,
      name: "measuring_spoons",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Offset Spatula",
      id: 1280511,
      name: "offset_spatula",
      parent_tag_name: null,
      root_tag_type: "equipment",
      type: "equipment",
    },
    {
      display_name: "Tips Viral",
      id: 6718867,
      name: "tips_viral",
      parent_tag_name: null,
      root_tag_type: "feature_page",
      type: "feature_page",
    },
    {
      display_name: "Cooking Style",
      id: 9295810,
      name: "cooking_style",
      parent_tag_name: null,
      root_tag_type: "cooking_style",
      type: "cooking_style",
    },
    {
      display_name: "Appliance",
      id: 9295811,
      name: "appliance",
      parent_tag_name: null,
      root_tag_type: "appliance",
      type: "appliance",
    },
    {
      display_name: "Meal",
      id: 9295813,
      name: "meal",
      parent_tag_name: null,
      root_tag_type: "meal",
      type: "meal",
    },
    {
      display_name: "Occasion",
      id: 9299134,
      name: "occasion",
      parent_tag_name: "seasonal",
      root_tag_type: "seasonal",
      type: "seasonal",
    },
    {
      display_name: "Chicken",
      id: 9299514,
      name: "chicken",
      parent_tag_name: "dinner",
      root_tag_type: "meal",
      type: "dinner",
    },
    {
      display_name: "Beef",
      id: 9299515,
      name: "beef",
      parent_tag_name: "dinner",
      root_tag_type: "meal",
      type: "dinner",
    },
    {
      display_name: "Baked Pasta",
      id: 9299621,
      name: "baked_pasta",
      parent_tag_name: "pasta",
      root_tag_type: "meal",
      type: "pasta",
    },
    {
      display_name: "Lasagna",
      id: 9299622,
      name: "lasagna",
      parent_tag_name: "pasta",
      root_tag_type: "meal",
      type: "pasta",
    },
    {
      display_name: "Meats",
      id: 10623507,
      name: "meats",
      parent_tag_name: "ingredients_to_avoid",
      root_tag_type: "ingredients_to_avoid",
      type: "ingredients_to_avoid",
    },
    {
      display_name: "Gluten",
      id: 10623589,
      name: "gluten",
      parent_tag_name: "allergens",
      root_tag_type: "ingredients_to_avoid",
      type: "allergens",
    },
    {
      display_name: "Dairy",
      id: 10623608,
      name: "dairy",
      parent_tag_name: "allergens",
      root_tag_type: "ingredients_to_avoid",
      type: "allergens",
    },
    {
      display_name: "Beef",
      id: 10623611,
      name: "beef",
      parent_tag_name: "meats",
      root_tag_type: "ingredients_to_avoid",
      type: "meats",
    },
    {
      display_name: "Chicken",
      id: 10623612,
      name: "chicken",
      parent_tag_name: "meats",
      root_tag_type: "ingredients_to_avoid",
      type: "meats",
    },
  ],
  thumbnail_alt_text: "",
  thumbnail_url:
    "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/150087.jpg",
  tips_and_ratings_enabled: true,
  topics: [
    {
      name: "Romantic Dinners",
      slug: "romantic-dinners",
    },
    {
      name: "Winter Recipes",
      slug: "winter",
    },
    {
      name: "Dinner",
      slug: "dinner",
    },
    {
      name: "Pasta",
      slug: "pasta",
    },
    {
      name: "American",
      slug: "american",
    },
    {
      name: "Italian",
      slug: "italian",
    },
  ],
  total_time_minutes: 450,
  total_time_tier: null,
  updated_at: 1683237600,
  user_ratings: {
    count_negative: 92,
    count_positive: 240,
    score: 0.7228915662650602,
  },
  video_ad_content: "none",
  video_id: 42294,
  video_url: "https://vid.tasty.co/output/89658/hls24_1523902408.m3u8",
  yields: "Servings: 20",
};
